spring:
  application:
    name: rescue-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.120.1.174:10024/rescue
    username: root
    password: 20010411LZH.
# 运行端口
server:
  port: 3088


#日志配置
logging:
  config: classpath:logback-spring.xml

#actuator管理
management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
