spring:
  application:
    name: rescue-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.120.1.174:10024/rescue
    username: root
    password: 20010411LZH.
# 运行端口
server:
  port: 3088


#日志配置
logging:
  config: classpath:logback-spring.xml

#actuator管理
management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaye.rescuebackend
# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn

#mybatis-plus配置控制台打印完整带参数的sql语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_uuid
