name: Build and push Docker image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/rescue-backend
    steps:

    - uses: actions/checkout@v3
      name: Checkout code

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        TAG=`${{GITHUB_REF#refs/*/}}`
        docker build -t ${{ env.IMAGE_NAME }}:${TAG} .

    - name: Push Docker image
      run: |
        TAG=`${{GITHUB_REF#refs/*/}}`
        docker push ${{ env.IMAGE_NAME }}:${TAG}
