name: Build and push Docker image

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/rescue-backend
    steps:

    - name: Checkout code
      uses: actions/checkout@v2.3.4

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        TAG=`echo "${{ github.ref }}" | sed 's/v//'`
        docker build -t ${{ env.IMAGE_NAME }}:${TAG} .

    - name: Push Docker image
      run: |
        TAG=`echo "${{ github.ref }}" | sed 's/v//'`
        docker push ${{ env.IMAGE_NAME }}:${TAG}
